### ISSUE TITLE
add batch commands to the api

### ISSUE THREAD

**Issue by AlexFiverr** [veny/orientdb4r#39]

**Comment by veny** [comment]
Usually a nice formulation containing 'please' or 'would you' increases my motivation to invest my time gratis for community.

**Comment by AlexFiverr** [comment]
Oh, hey, sorry - I was just following the convention of your previous issues without noticing that they were all created by you :) 
My bad man - Your support and contribution is of course much appreciated from all of our R&D team here at www.fiverr.com

**Comment by veny** [comment]
nothing happened.

is a pleasure to hear that my component is used in real solution. I try to implement the feature in next week.

**Comment by AlexFiverr** [comment]
thanks!

**Comment by veny** [comment]
done, released in v0.5.1

updated https://github.com/veny/orientdb4r/wiki/Samples-Document-CRUD

enjoy!
